### ISSUE TITLE
咨询：博客代码和主题能否使用？

### ISSUE THREAD

**Issue by osirismin** [pinky-pig/arvin#1]
您好，我是代码小白，最近想入坑折腾一个博客，请您的博客代码和主题是否开源，我能否使用？

**Comment by pinky-pig** [comment]
可以的。不过 `blog/`文件夹下的我的个人博客内容需要删除

**Comment by osirismin** [comment]
好嘞，这个我懂……另外反馈一下，首页模块组件拖动的效果在平板端使用的时候不太流畅，建议可以弄个屏幕尺寸限制ban掉，或者优化一下。

**Comment by pinky-pig** [comment]
最新的代码，在 iPad 上禁止拖拽了，我现在这里没有设备，你可以看一下🤣

之前做过处理，但是 iPad `navigator.useragent` 从 `iPad` 变成 `Macintosh` ，忘记更新代码了，现在加上了。

[Code file](https://github.com/pinky-pig/arvin/blob/main/src/pages/bento.vue)

[Portfolio website online](https://mmeme.me/)

**Comment by osirismin** [comment]
> 之前做过处理，但是 iPad `navigator.useragent` 从 `iPad` 变成 `Macintosh` ，忘记更新代码了，现在加上了。


这么做会产生一个问题，iOS13 以前 navigator.platform 返回"iPhone"或"iPad"；iOS13 以后的 iPad，navigator.platform 返回"MacIntel"，相当于 Mac。如果加了Macintosh，会导致Mac设备在浏览时也被禁止拖拽，失去了这个主题的灵魂。

我是这么处理的：
// 检测是否是iPad，由于目前还没有触摸屏的 Mac，所以可以通过最大触控点来区分 Mac 和 iPad 。
const isIpad = (navigator.userAgent.match(/(iPad)/) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1))
const isIpadRef = ref(isIpad)
const disabled = ref(isMobileRef.value || isIpadRef.value)

**Comment by pinky-pig** [comment]
前几天有事情忙了🤣
其实是可以支持 iPad 或者移动端拖拽的，只不过之前一直偷懒🤣
本来设计是只在手机端ban掉拖拽，因为屏幕太小，上下滑动的时候可能无法判断是拖拽还是页面滑动。

我又提交了一下代码，将上次 `Macintosh` 的注释了，给拖拽的元素添加 CSS `touch-action: none;` ，之前在 pad 端拖拽卡顿的现象应该有所解决🤣

可以添加我的微信，有啥疑问我尽力帮忙解决: Arvin_wwb 😆
