### ISSUE TITLE
很赞，哈哈，超喜欢https://nevflynn.com/风格的布局~

### ISSUE THREAD

**Issue by Leizhenpeng** [pinky-pig/arvin#2]

**Comment by Leizhenpeng** [comment]
没想到还有vue的组件！

**Comment by pinky-pig** [comment]
哈哈，就是根据 nevflynn 的风格来的。😆
[nevflynn](https://nevflynn.com/) 使用的组件是 react-grid-layout ，不过我之前第一版本是 nuxt3 写的，没有找到好用的组件，就自己手写了一个拖拽(之前写过不少拖拽🤣)。
vue 组件有个 [vue-grid-layout](https://jbaysolutions.github.io/vue-grid-layout/)，不知道好不好用。我手写的这个 [bento](https://www.npmjs.com/package/v3-bento) 代码功能比较单一， absolute transform 定位，mousemove 拖拽，贪心计算位置。
